platform :ios, '11.4'

target 'StudioGhibliMovies' do
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftLint'
  pod 'SnapKit'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
  end

end


